
Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/trusty64"
  
#  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.network :private_network, ip: "192.168.60.102"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "256"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]   
  end  

  config.vm.provision :puppet do |puppet|
    puppet.module_path = "./modules"
  end
end


